/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.net.*;
import java.io.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Supun Sadeepa
 */
public class terminal extends javax.swing.JFrame {

    /**
     * Creates new form terminal
     */
    
    int mousepX = 0;
    int mousepY = 0;
    
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dos;
    
    public terminal() {
        initComponents();
        setIcon();
        this.setBackground(new Color(0,0,0,0));
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Resources/Ham.png")));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cmb3 = new javax.swing.JComboBox<>();
        spn3 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmb1 = new javax.swing.JComboBox<>();
        spn1 = new javax.swing.JSpinner();
        lbl1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        spn2 = new javax.swing.JSpinner();
        cmb2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        pnl1 = new javax.swing.JPanel();
        rmbtn = new javax.swing.JButton();
        clbtn = new javax.swing.JButton();
        cnbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("King Burger - Terminal");
        setBackground(new java.awt.Color(57, 70, 82));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 150, 150), 3, true));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drinks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        cmb3.setBackground(new java.awt.Color(0, 102, 255));
        cmb3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        cmb3.setForeground(new java.awt.Color(51, 51, 51));
        cmb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca Cola", "Pepsi", "Fanta", "SevenUp", "Sprite" }));
        cmb3.setToolTipText("Choose Drinks");
        cmb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb3ItemStateChanged(evt);
            }
        });

        spn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spn3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spn3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn3StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spn3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spn3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name/ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1.setToolTipText("Enter your name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Burgers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        cmb1.setBackground(new java.awt.Color(0, 51, 102));
        cmb1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        cmb1.setForeground(new java.awt.Color(51, 51, 51));
        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bacon Burger", "Umami Burger", "Pug Burger", "Green-Chile Burgers", "Minetta Burger" }));
        cmb1.setToolTipText("Choose Burgers");
        cmb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb1ItemStateChanged(evt);
            }
        });

        spn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spn1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spn1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spn1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Welcome to King Burger! How can I help you?");
        lbl1.setAutoscrolls(true);
        lbl1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbl1.setFocusable(false);
        lbl1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl1MouseDragged(evt);
            }
        });
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl1MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pizza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        spn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spn2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spn2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn2StateChanged(evt);
            }
        });

        cmb2.setBackground(new java.awt.Color(0, 102, 255));
        cmb2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        cmb2.setForeground(new java.awt.Color(51, 51, 51));
        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Neapolitan Pizza", "Chicago Pizza", "Sicilian Pizza", "Greek Pizza", "California Pizza" }));
        cmb2.setToolTipText("Choose Pizza");
        cmb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spn2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmb2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(spn2))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        tbl1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Price (Rs)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl1.setGridColor(new java.awt.Color(153, 153, 153));
        tbl1.setRowHeight(25);
        tbl1.setRowMargin(5);
        tbl1.setSelectionBackground(new java.awt.Color(51, 102, 255));
        tbl1.setShowHorizontalLines(false);
        tbl1.setShowVerticalLines(false);
        tbl1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tbl1MouseDragged(evt);
            }
        });
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        pnl1.setBackground(new java.awt.Color(0, 51, 102));
        pnl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnl1.setEnabled(false);

        rmbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        rmbtn.setText("Remove");
        rmbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rmbtn.setEnabled(false);
        rmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmbtnActionPerformed(evt);
            }
        });

        clbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clbtn.setText("Clear All");
        clbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clbtn.setEnabled(false);
        clbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clbtnActionPerformed(evt);
            }
        });

        cnbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cnbtn.setText("Confirm");
        cnbtn.setToolTipText("Continue to checkout");
        cnbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cnbtn.setEnabled(false);
        cnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cnbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("About..");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lbl1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void disablebtn(){
        txt1.setEnabled(false);
        cmb1.setEnabled(false);
        cmb2.setEnabled(false);
        cmb3.setEnabled(false);
        
        spn1.setEnabled(false);
        spn2.setEnabled(false);
        spn3.setEnabled(false);
    }
    
    public static void enablebtn(){
        txt1.setEnabled(true);
        cmb1.setEnabled(true);
        cmb2.setEnabled(true);
        cmb3.setEnabled(true);
        
        spn1.setEnabled(true);
        spn2.setEnabled(true);
        spn3.setEnabled(true);
    }
    
    private void spn1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn1StateChanged

        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        
        int price = 0;
        int total = 0;
        
        switch(cmb1.getSelectedIndex()){
            case 0: price = 90; break;
            case 1: price = 120; break;
            case 2: price = 150; break;
            case 3: price = 130; break;
            case 4: price = 250; break;
        }
        
        price *= Integer.parseInt(spn1.getValue().toString());
        
        if(dm.getRowCount() == 0 && !spn1.getValue().equals(0)){
            dm.addRow(new Object[]{cmb1.getSelectedItem(),spn1.getValue(),price});
        }else{
            for(int i = 0; i < dm.getRowCount(); i++){
                if(cmb1.getSelectedItem().equals(dm.getValueAt(i, 0))){
                    dm.setValueAt(spn1.getValue(), i, 1);
                    dm.setValueAt(price, i, 2);
                    if(spn1.getValue().equals(0)){
                        dm.removeRow(i);
                    }
                    break;
                }
                if(i+1 == dm.getRowCount()){
                    dm.addRow(new Object[]{cmb1.getSelectedItem(),spn1.getValue(),price});
                }
            }
        }
        
        for(int i = 0; i < dm.getRowCount(); i++){
            total += Integer.parseInt(dm.getValueAt(i, 2).toString());
        }
        
        if(dm.getRowCount() == 0){
            lbl1.setText("Welcome to King Burger! How can I help you?");
        }else{
            lbl1.setText("Total Rs: " + total + "/=");
        }        
        
        if(dm.getRowCount() != 0){
            cnbtn.setEnabled(true);
            rmbtn.setEnabled(true);
            clbtn.setEnabled(true);
        }else{
            cnbtn.setEnabled(false);
            rmbtn.setEnabled(false);
            clbtn.setEnabled(false);
        }
                
    }//GEN-LAST:event_spn1StateChanged

    private void cmb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb1ItemStateChanged
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        for(int i = 0; i < tbl1.getRowCount(); i++){
            if(cmb1.getSelectedItem().equals(tbl1.getValueAt(i, 0))){
                spn1.setValue(dm.getValueAt(i, 1));
                break;
            }
            if(i+1 == dm.getRowCount()){
                spn1.setValue(0);
            }
        }
    }//GEN-LAST:event_cmb1ItemStateChanged

    private void spn2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn2StateChanged
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        
        int price = 0;
        int total = 0;
        
        switch(cmb2.getSelectedIndex()){
            case 0: price = 900; break;
            case 1: price = 1100; break;
            case 2: price = 1300; break;
            case 3: price = 1400; break;
            case 4: price = 1500; break;
        }
        
        price *= Integer.parseInt(spn2.getValue().toString());
        
        if(dm.getRowCount() == 0 && !spn2.getValue().equals(0)){
            dm.addRow(new Object[]{cmb2.getSelectedItem(),spn2.getValue(),price});
        }else{
            for(int i = 0; i < dm.getRowCount(); i++){
                if(cmb2.getSelectedItem().equals(dm.getValueAt(i, 0))){
                    dm.setValueAt(spn2.getValue(), i, 1);
                    dm.setValueAt(price, i, 2);
                    if(spn2.getValue().equals(0)){
                        dm.removeRow(i);
                    }
                    break;
                }
                if(i+1 == dm.getRowCount()){
                    dm.addRow(new Object[]{cmb2.getSelectedItem(),spn2.getValue(),price});
                }
            }
        }
        
        for(int i = 0; i < dm.getRowCount(); i++){
            total += Integer.parseInt(dm.getValueAt(i, 2).toString());
        }
        
        if(dm.getRowCount() == 0){
            lbl1.setText("Welcome to King Burger! How can I help you?");
        }else{
            lbl1.setText("Total Rs: " + total + "/=");
        }
        
        if(dm.getRowCount() != 0){
            cnbtn.setEnabled(true);
            rmbtn.setEnabled(true);
            clbtn.setEnabled(true);
        }else{
            cnbtn.setEnabled(false);
            rmbtn.setEnabled(false);
            clbtn.setEnabled(false);
        }
        
    }//GEN-LAST:event_spn2StateChanged

    private void cmb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb2ItemStateChanged
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        for(int i = 0; i < tbl1.getRowCount(); i++){
            if(cmb2.getSelectedItem().equals(tbl1.getValueAt(i, 0))){
                spn2.setValue(dm.getValueAt(i, 1));
                break;
            }
            if(i+1 == dm.getRowCount()){
                spn2.setValue(0);
            }
        }
    }//GEN-LAST:event_cmb2ItemStateChanged

    private void spn3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn3StateChanged
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        
        int price = 0;
        int total = 0;
        
        switch(cmb3.getSelectedIndex()){
            case 0: price = 180; break;
            case 1: price = 170; break;
            case 2: price = 190; break;
            case 3: price = 160; break;
            case 4: price = 175; break;
        }
        
        price *= Integer.parseInt(spn3.getValue().toString());
        
        if(dm.getRowCount() == 0 && !spn3.getValue().equals(0)){
            dm.addRow(new Object[]{cmb3.getSelectedItem(),spn3.getValue(),price});
        }else{
            for(int i = 0; i < dm.getRowCount(); i++){
                if(cmb3.getSelectedItem().equals(dm.getValueAt(i, 0))){
                    dm.setValueAt(spn3.getValue(), i, 1);
                    dm.setValueAt(price, i, 2);
                    if(spn3.getValue().equals(0)){
                        dm.removeRow(i);
                    }
                    break;
                }
                if(i+1 == dm.getRowCount()){
                    dm.addRow(new Object[]{cmb3.getSelectedItem(),spn3.getValue(),price});
                }
            }
        }
        
        for(int i = 0; i < dm.getRowCount(); i++){
            total += Integer.parseInt(dm.getValueAt(i, 2).toString());
        }
        
        if(dm.getRowCount() == 0){
            lbl1.setText("Welcome to King Burger! How can I help you?");
        }else{
            lbl1.setText("Total Rs: " + total + "/=");
        }
        
        if(dm.getRowCount() != 0){
            cnbtn.setEnabled(true);
            rmbtn.setEnabled(true);
            clbtn.setEnabled(true);
        }else{
            cnbtn.setEnabled(false);
            rmbtn.setEnabled(false);
            clbtn.setEnabled(false);
        }
    }//GEN-LAST:event_spn3StateChanged

    private void cmb3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb3ItemStateChanged
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        for(int i = 0; i < tbl1.getRowCount(); i++){
            if(cmb3.getSelectedItem().equals(tbl1.getValueAt(i, 0))){
                spn3.setValue(dm.getValueAt(i, 1));
                break;
            }
            if(i+1 == dm.getRowCount()){
                spn3.setValue(0);
            }
        }
    }//GEN-LAST:event_cmb3ItemStateChanged

    private void rmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmbtnActionPerformed
        
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        
        int total = 0;
        
        for(int i = 0; i < dm.getRowCount(); i++){
            if(tbl1.isRowSelected(i)){
                dm.removeRow(tbl1.getSelectedRow());
            }
        }
        
        for(int i = 0; i < dm.getRowCount(); i++){
            total += Integer.parseInt(dm.getValueAt(i, 2).toString());
        }
        
        if(dm.getRowCount() == 0){
            lbl1.setText("Welcome to King Burger! How can I help you?");
        }else{
            lbl1.setText("Total Rs: " + total + "/=");
        }
        
        if(dm.getRowCount() != 0){
            cnbtn.setEnabled(true);
            rmbtn.setEnabled(true);
            clbtn.setEnabled(true);
        }else{
            cnbtn.setEnabled(false);
            rmbtn.setEnabled(false);
            clbtn.setEnabled(false);
        }
        
    }//GEN-LAST:event_rmbtnActionPerformed

    private void clbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clbtnActionPerformed
        // TODO add your handling code here:
        tbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Price (Rs)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        int total = 0;
        
        for(int i = 0; i < dm.getRowCount(); i++){
            total += Integer.parseInt(dm.getValueAt(i, 2).toString());
        }
        
        lbl1.setText("Welcome to King Burger! How can I help you?");
                
        cnbtn.setEnabled(false);
        rmbtn.setEnabled(false);
        clbtn.setEnabled(false);
        
    }//GEN-LAST:event_clbtnActionPerformed

    private void cnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnbtnActionPerformed
        DefaultTableModel dm = (DefaultTableModel) tbl1.getModel();
        
        disablebtn();
        
        try {
            
            dos.writeUTF(txt1.getText());
            dos.writeUTF(String.valueOf(dm.getRowCount()));
            for(int i = 0; i < dm.getRowCount(); i++){
                for(int j = 0; j < dm.getColumnCount(); j++){
                    dos.writeUTF(tbl1.getValueAt(i,j).toString());
                }
            }
            
        } catch (Exception e) {}
        
        lbl1.setText("Confirmed! Please move to Outlet.");
        txt1.setText("");
        dm.setRowCount(0);
        cnbtn.setEnabled(false);
        rmbtn.setEnabled(false);
        clbtn.setEnabled(false);
        spn1.setValue(0);
        spn2.setValue(0);
        spn3.setValue(0);
   
    }//GEN-LAST:event_cnbtnActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
        
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void lbl1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_lbl1MouseDragged

    private void lbl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_lbl1MousePressed

    private void tbl1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
        
    }//GEN-LAST:event_tbl1MouseDragged

    private void tbl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_tbl1MousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This program is developed by S.S. Wickramasinghe for ICT2406\nThank you for using.", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel1MouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new terminal().setVisible(true);
                
            }
        });
        
        String msg = "";
        
        try {
            s = new Socket("127.0.0.1", 3000);
            dos = new DataOutputStream(s.getOutputStream());

            dis = new DataInputStream(s.getInputStream());
            
            while(true){
                msg = dis.readUTF();

                lbl1.setText("Welcome to King Burger! How can I help you?");

                if(msg.equals("done")){
                    enablebtn();
                }
            }
            
        } catch (Exception e) {}
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clbtn;
    private static javax.swing.JComboBox<String> cmb1;
    private static javax.swing.JComboBox<String> cmb2;
    private static javax.swing.JComboBox<String> cmb3;
    private javax.swing.JButton cnbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lbl1;
    private javax.swing.JPanel pnl1;
    private static javax.swing.JButton rmbtn;
    private static javax.swing.JSpinner spn1;
    private static javax.swing.JSpinner spn2;
    private static javax.swing.JSpinner spn3;
    private static javax.swing.JTable tbl1;
    private static javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
